
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRO260_Team2Project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Comment
    {
        [ForeignKey("ImageOwner")]
        [Column(Order = 0)]
        public int ImageID { get; set; }
        [ForeignKey("ImageOwner")]
        [Column(Order = 1)]
        public int OwnerID { get; set; }
        public int PosterID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Content { get; set; }
        [Key]
        public int CommentID { get; set; }

        public virtual ImageOwner ImageOwner { get; set; }
    }
}
