
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRO260_Team2Project
{

using System;
    using System.Collections.Generic;
    
public partial class Image
{

    public Image()
    {

        this.Flags = new HashSet<Flag>();

        this.ImageTags = new HashSet<ImageTag>();

    }


    public int ImageID { get; set; }

    public System.DateTime DateOfUpload { get; set; }

    public int OriginalPosterID { get; set; }

    public byte[] Image1 { get; set; }



    public virtual ICollection<Flag> Flags { get; set; }

    public virtual ICollection<ImageTag> ImageTags { get; set; }

}

}
