//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Team2Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTag
    {
        [Key]
        public int ImageID { get; set; }
        public string Tag { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
