//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Team2Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Comments = new HashSet<Comment>();
            this.Comments1 = new HashSet<Comment>();
            this.ImageOwners = new HashSet<ImageOwner>();
        }
    
        [Key]
        public int MemberID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public long AccountBalance { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Comment> Comments1 { get; set; }
        public virtual ICollection<ImageOwner> ImageOwners { get; set; }
    }
}
