//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2Project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class webpages_OAuthMembership
    {
        [Key]
        [Column(Order = 0)]
        public string Provider { get; set; }
        [Key]
        [Column(Order = 1)]
        public string ProviderUserId { get; set; }
        public int UserId { get; set; }
    }
}